name: Storybook Deploy
on:
  push:
    branches:
      - main

jobs:
  storybook-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: yarn install

      - name: Publish to Chromatic
          uses: chromaui/action@v1

        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}